version: '3'

services:
  record:
    build: .
    image: redis-record
    container_name: redis-record
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./recordings:/src/recordings
    restart: unless-stopped

  replay:
    build: .
    image: redis-record
    container_name: redis-replay
    command: -m redis_record.replay
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./recordings:/src/recordings
    restart: unless-stopped

  # # Remove this if you already have a redis instance
  # redis:
  #   image: redis/redis-stack
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #     - 8001:8001
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping healthcheck | grep healthcheck"]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  default:
    name: redis-streamer_default
    external: true